/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Hospital_Management_System;

import java.awt.geom.Area;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rohan Shinde
 */
public class EditRecordsPatient extends javax.swing.JFrame {

    /**
     * Creates new form EditRecordsPatient
     */
    public EditRecordsPatient() {
        initComponents();
        patientID.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        patientID = new javax.swing.JTextField();
        disease = new javax.swing.JTextField();
        patientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PContactNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PAge = new javax.swing.JTextField();
        updatePatient = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        deleteP = new javax.swing.JButton();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        doctorName2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        wardRoom = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        VPRecords = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        backEP = new javax.swing.JButton();
        logout5 = new javax.swing.JButton();
        print2 = new javax.swing.JButton();
        searchPat = new javax.swing.JTextField();
        search2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Edit Patient Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(253, 217, 108));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Contact No:");

        patientID.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        disease.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        patientName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        patientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Patient ID:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Patient Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Disease:");

        PContactNo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Date:");

        PAge.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        updatePatient.setBackground(new java.awt.Color(0, 204, 51));
        updatePatient.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updatePatient.setText("UPDATE");
        updatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePatientActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Gender:");

        date.setDateFormatString("yyyy-MM-dd");
        date.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        deleteP.setBackground(new java.awt.Color(255, 102, 102));
        deleteP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteP.setText("DELETE");
        deleteP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbMale);
        rbMale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbMale.setText("Male");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbFemale.setText("Female");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Age:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Doctor Name:");

        doctorName2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        doctorName2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rahul Shinde(Child Specialist)", "Manali Vangule(Skin Specialist)", "Mrunal Sharma(Obstetrician)", "Neha Dhupia(Surgeon)", "Mohit Saxena(Therapist)", "Rohan Malhotra(Psychologist)", "Sujal Singh(Cancer Specialist)", "Sahil Singh(Diabetes)", "Roshan Sharma(Heart Specialist)", "Swapnil Mhatre(Eye Specialist)" }));
        doctorName2.setSelectedItem(null);

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("PAY BILL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Ward Room:");

        wardRoom.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        wardRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General Ward", "Special Ward", "Acute Care Units", "ICU Ward", "Accidental & Emergency", "Maternity Ward", "Paediatrics Ward" }));
        wardRoom.setSelectedItem(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(rbMale)
                                .addGap(24, 24, 24)
                                .addComponent(rbFemale))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(wardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 6, Short.MAX_VALUE)
                                .addComponent(updatePatient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(doctorName2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(patientID, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(disease))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PAge, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(patientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(patientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(disease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbMale)
                    .addComponent(rbFemale)
                    .addComponent(jLabel8)
                    .addComponent(PAge, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(doctorName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(wardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePatient)
                    .addComponent(deleteP)
                    .addComponent(jButton1))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        VPRecords.setBackground(new java.awt.Color(255, 153, 0));
        VPRecords.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        VPRecords.setText("VIEW RECORDS");
        VPRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VPRecordsActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Disease", "Contact No", "Gender", "Age", "Date", "Doctor Name", "Ward Room"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        backEP.setBackground(new java.awt.Color(153, 153, 153));
        backEP.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backEP.setText("BACK");
        backEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEPActionPerformed(evt);
            }
        });

        logout5.setBackground(new java.awt.Color(255, 51, 0));
        logout5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logout5.setText("LOGOUT");
        logout5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout5ActionPerformed(evt);
            }
        });

        print2.setBackground(new java.awt.Color(255, 153, 153));
        print2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        print2.setText("PRINT");
        print2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print2ActionPerformed(evt);
            }
        });

        search2.setBackground(new java.awt.Color(153, 102, 255));
        search2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        search2.setText("SEARCH");
        search2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(backEP)
                                .addGap(224, 224, 224)
                                .addComponent(print2)
                                .addGap(211, 211, 211)
                                .addComponent(logout5))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(VPRecords)
                        .addGap(49, 49, 49)
                        .addComponent(searchPat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(search2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VPRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchPat, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backEP)
                    .addComponent(logout5)
                    .addComponent(print2))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEPActionPerformed
        PatientRecord p = new PatientRecord();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_backEPActionPerformed

    private void logout5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout5ActionPerformed
        loginPage l = new loginPage();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout5ActionPerformed

    private void patientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    private void updatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePatientActionPerformed
        
        try{
            String PID=patientID.getText();
            String pName=patientName.getText();
            String Disease=disease.getText();
            String ContactNo=PContactNo.getText();
            String Gender;
            if(rbMale.isSelected()){
                Gender="Male";
            }
            else if(rbFemale.isSelected())
            {
                Gender="Female";
            }
            else
            {
                Gender="";
            }
            String Age=PAge.getText();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(this.date.getDate());
            String doct_name=doctorName2.getSelectedItem().toString();
            String Ward_Room=wardRoom.getSelectedItem().toString();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/HospitalManagementSystem","root","Rohan@123");
            PreparedStatement ptst=con.prepareStatement("update PatientRecord set patientName=?,disease=?,contactNo=?,Gender=?,Age=?,Date=?,DoctorName=?,WardRoom=? where patientID=?");
            
                
                ptst.setString(1,pName);
                ptst.setString(2,Disease);
                ptst.setString(3,ContactNo);
                ptst.setString(4,Gender);
                ptst.setString(5,Age);
                ptst.setString(6, date);
                ptst.setString(7, doct_name);
                ptst.setString(8, Ward_Room);
                ptst.setString(9, PID);
                

                ptst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "data Updated Sucessfully");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updatePatientActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int pid=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
        try{
           Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HospitalManagementSystem","root","Rohan@123");
            Statement st=con.createStatement();
            ResultSet res=st.executeQuery("select * from PatientRecord  where patientID="+pid);
            while(res.next()){
                patientID.setText(res.getString("patientID"));
                patientName.setText(res.getString("patientName"));
                disease.setText(res.getString("disease"));
                PContactNo.setText(res.getString("contactNo"));
                if(res.getString("Gender").equals("Male"))
                {
                    rbMale.setSelected(true);
                }
                else if(res.getString("Gender").equals("Female"))
                {
                    rbFemale.setSelected(true);
                }
                else
                {
                    buttonGroup2.clearSelection();
                }
                PAge.setText(res.getString("Age"));
                date.setDate(res.getDate("Date"));
                doctorName2.setSelectedItem(res.getString("DoctorName"));
                wardRoom.setSelectedItem(res.getString("WardRoom"));
            }
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_jTable2MouseClicked

    private void VPRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VPRecordsActionPerformed
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/HospitalManagementSystem","root","Rohan@123");
            
            Statement st=con.createStatement();
            String sql="select * from PatientRecord";
            PreparedStatement ptst = con.prepareStatement(sql);
            ResultSet rs = ptst.executeQuery();
            DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
            tm.setRowCount(0);
            while(rs.next()){
               Object o[]={rs.getString("patientID"),rs.getString("patientName"),rs.getString("disease"),rs.getString("contactNo"),rs.getString("Gender"),rs.getString("Age"),rs.getString("Date"),rs.getString("DoctorName"),rs.getString("WardRoom")};
               tm.addRow(o);
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_VPRecordsActionPerformed
    }
    private void deletePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePActionPerformed
         int pID=Integer.parseInt(jTable2.getValueAt(jTable2.getSelectedRow(),0).toString());
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/HospitalManagementSystem","root","Rohan@123");
            Statement st = con.createStatement();
            int r=JOptionPane.showConfirmDialog(this, "Are you sure you want to delete selected row");
            if(r==0){
              if(!st.execute("delete from PatientRecord where patientID="+pID)){
                  JOptionPane.showMessageDialog(this, "Data deleted Successfully");
                  formWindoeOpened(null);
              }
            }else{
                
            }       
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_deletePActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         String PID=patientID.getText();
         String pName=patientName.getText();
         String Disease=disease.getText();
         String docName=doctorName2.getSelectedItem().toString();
         String wardroom = wardRoom.getSelectedItem().toString();
         double Total_Price=0;
         
         if(wardroom.equalsIgnoreCase("General Ward"))
         {
             Total_Price=3000;
         }
         else if(wardroom.equalsIgnoreCase("Special Ward"))
         {
             Total_Price=7000;
         }
         else if(wardroom.equalsIgnoreCase("Acute Care Units"))
         {
             Total_Price=1000;
         }
         else if(wardroom.equalsIgnoreCase("ICU Ward"))
         {
             Total_Price=40000;
         }
         else if(wardroom.equalsIgnoreCase("Accidental & Emergency"))
         {
             Total_Price=50000;
         }
         else if(wardroom.equalsIgnoreCase("Maternity Ward"))
         {
             Total_Price=70000;
         }
         else if(wardroom.equalsIgnoreCase("Paediatrics Ward"))
         {
             Total_Price=1800;
         }
         else
         {
             JOptionPane.showMessageDialog(this, "You need to select ward Room");
         }
         JOptionPane.showMessageDialog(this, " ******* BILL *******\n\n Patient ID: "+PID+"\n Patient Name: "+pName+"\n Disease: "+Disease+"\n Doctor Name:"+docName+"\n Ward Room: "+wardroom+"\n Total Bill Amount: "+Total_Price);
         
         Bill b = new Bill();
         
         
        
       
        b.area.setText("*************************************************************\n"+"******                             SHINDE HOSPITAL                         ******\n"+
                "*************************************************************\n\n"+" Patient ID: "+patientID.getText()+"\n\n"+" Patient Name: "+
                patientName.getText()+"\n\n"+" Disease: "+disease.getText()+"\n\n"+" Doctor Name: "+doctorName2.getSelectedItem()+
                "\n\n"+" Ward Room: "+wardRoom.getSelectedItem()+"\n\n"+" Total Bill: "+Total_Price+"\n\n\n"+"                                                                        Signature" );
        
        b.setVisible(true);
       dispose();
       
         
         
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void print2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print2ActionPerformed
        // TODO add your handling code here:
        try{
            jTable2.print();

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_print2ActionPerformed

    private void search2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tm = (DefaultTableModel)jTable2.getModel();
        TableRowSorter<DefaultTableModel> obj=new TableRowSorter<>(tm);
        jTable2.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(searchPat.getText()));
    }//GEN-LAST:event_search2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditRecordsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditRecordsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditRecordsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditRecordsPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditRecordsPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PAge;
    private javax.swing.JTextField PContactNo;
    private javax.swing.JButton VPRecords;
    private javax.swing.JButton backEP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton deleteP;
    private javax.swing.JTextField disease;
    private javax.swing.JComboBox<String> doctorName2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logout5;
    private javax.swing.JTextField patientID;
    private javax.swing.JTextField patientName;
    private javax.swing.JButton print2;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JButton search2;
    private javax.swing.JTextField searchPat;
    private javax.swing.JButton updatePatient;
    private javax.swing.JComboBox<String> wardRoom;
    // End of variables declaration//GEN-END:variables

    private void formWindoeOpened(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
